### ISSUE TITLE
Als projectleider wil ik een projectlid toevoegen aan het project zodat alle projectleden beschikking hebben over dezelfde informatie

### ISSUE THREAD

**Issue by fniessink** [mxipartners/mijnmxi#7]

**Comment by fniessink** [comment]
Projectleden toevoegen kan al in de huidige versie, alleen kan iedereen het; niet alleen de projectleider.

**Comment by ErikOnBike** [comment]
Qua opzet zou het logisch zijn dat je naast 'bekende' projectleden ook externen kunt uitnodigen door hen een email te sturen. In zo'n geval zou toegang tot de applicatie via email-adres (ipv username) handig(er?) zijn. Je wilt namelijk zekerheid over wie je aan je project koppelt (niet alleen afgaan op een username die iemand bedacht heeft). Alle M&I-ers (email-adres eindigend op @mxi.nl) mogen altijd account aanmaken en projecten aanmaken (kunnen immers allemaal projectleider zijn). Een projectleider nodigt vervolgens deelnemers uit.
